# Generated by Django 4.2.6 on 2023-11-07 15:28

from django.db import migrations, models
import django.db.models.deletion
import school_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_emp', models.CharField(max_length=20)),
                ('middle_name_emp', models.CharField(max_length=20)),
                ('first_name_emp', models.CharField(max_length=20)),
                ('date_birth_emp', models.DateField()),
                ('email_emp', models.CharField(max_length=100)),
                ('number_emp', models.CharField(max_length=15, validators=[school_app.models.validate_phone_number])),
                ('passport_detail_emp', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=100)),
                ('address_emp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_pupil', models.CharField(max_length=20)),
                ('middle_name_pupil', models.CharField(max_length=20)),
                ('first_name_pupil', models.CharField(max_length=20)),
                ('date_birth_pupil', models.DateField()),
                ('date_reception', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_parent', models.CharField(max_length=20)),
                ('middle_name_parent', models.CharField(max_length=20)),
                ('first_name_parent', models.CharField(max_length=20)),
                ('date_birth_parent', models.DateField()),
                ('passport_detail_parent', models.CharField(max_length=10)),
                ('address_parent', models.CharField(max_length=200)),
                ('number_parent', models.CharField(max_length=12, validators=[school_app.models.validate_phone_number])),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.employee')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Refused'), (3, 'Executed'), (4, 'Signed')])),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.employee')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.parent')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Refused'), (3, 'Executed')])),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.employee')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.parent')),
            ],
        ),
    ]
