# Generated by Django 4.2.6 on 2023-11-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявление', 'verbose_name_plural': 'Заявления'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Ребёнок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelTable(
            name='application',
            table='Application',
        ),
        migrations.AlterModelTable(
            name='document',
            table='Document',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
        migrations.AlterModelTable(
            name='parent',
            table='Parent',
        ),
        migrations.AlterModelTable(
            name='pupil',
            table='Pupil',
        ),
    ]
